### ISSUE TITLE
Consider adding a hardware-specific license

### ISSUE THREAD

**Issue by parker-research** [ezrafielding/vertecs-ccb#1]
Very neat project!

Consider adding a hardware-specific, like the [CERN-OHL-P-2.0 Open Hardware License](https://choosealicense.com/licenses/cern-ohl-p-2.0/)! The MIT License is technically only applicable for software.

Good comparison/list of some options: https://choosealicense.com/non-software/

**Comment by ezrafielding** [comment]
Great suggestion, thanks!
I've gone ahead and changed to the hardware-specific license.

**Comment by parker-research** [comment]
Very awesome! :)

Is there a software component of this that'll be shared in the future? Also curious about the full Bill of Materials (BOM) for off-board components

**Comment by ezrafielding** [comment]
We may release a software component some time in future when mission software is complete. Many of the commands we need to issue over the software are proprietary. But maybe we'll make a release of basic example functions. We do already mention what to expect with software in the associated paper (Raspberry Pi OS Lite as the OS and Python and C for mission software).

A BOM for off-board components also sounds like a great idea. Hopefully I can get around to that in the near future. I'll need to figure out what of those are actually publicly available. For now, I'd recommend checking the data sheets of each connector for the appropriate plug to use with it, and comparing that to the schematic for what to connect where. (The paper also has some nice pictures showing how everything plugs in together)
